import "./globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { NextAuthProvider } from "@/contexts/NextAuthProvider";
import { Web3Provider } from "@/contexts/Web3Provider";
import { config } from "./lib/wagmi";
import { cookieToInitialState } from "wagmi";
import { getServerSession } from "./api/authOptions";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config,headers().get('cookie'));
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Provider initialState={initialState}>
          <NextAuthProvider session={session}>
            {children}
          </NextAuthProvider>
        </Web3Provider>
      </body>
    </html>
  );
}
